### ISSUE TITLE
djangoforms replacement or python 2.7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dvska/appengine-admin#30]
```
We are looking for a solution and I found that also appengine_admin uses 
djangoforms which are not available when upgrading to 2.7. Did you think of a 
solution yet? We are discussing it in the google group today:

We've used http://wtforms.simplecodes.com/ in a few WSGI apps.

Might be worth a look, has some great features.

On Mon, Oct 31, 2011 at 7:34 PM, Niklas R <niklasro@gmail.com> wrote:
> Hi
> My app is upgrading to python 2.7 and used the djangoforms and now with
> python 2.7  I must get out of it since it is no longer included with the
> python 2.7:
>
>  from google.appengine.ext.db import djangoforms
> ImportError: cannot import name djangoforms
>
> So I'm considering choosing a complete new form framework while in the
> meantime I just patch in djangoforms. Or do you think I should continue to
> patch in djangoforms since I also patch in the django.paginator and I
> actually quite like it that I can do that? I looked at some form framework
> and I want it to be able to do validation and preferably also form preview.
> Am I better off creating my own form handling than looking for a form
> framework since I can't find one that can do preview?
>
> Thank you
```

Original issue reported on code.google.com by `nikla...@gmail.com` on 31 Oct 2011 at 3:18
